### ISSUE TITLE
Camera/Galeria não abre

### ISSUE THREAD

**Issue by lopesluizfelipe** [vanerjm/lepapp_mobile#3]
Quando fiz o cadastro para profissional, ao clicar em foto, não abre a camera e nem a galeria.

![WhatsApp Image 2020-11-15 at 10 43 13](https://user-images.githubusercontent.com/74273780/99186538-a596c600-272f-11eb-91eb-8716b3e87666.jpeg)

**Comment by vanerjm** [comment]
Problema de permissão em builds oficiais (release).
