### ISSUE TITLE
Localização - cadastro de profissional

### ISSUE THREAD

**Issue by lopesluizfelipe** [vanerjm/lepapp_mobile#4]
Após colocar o CEP, salvei e continuei. Porém abriu essa tela e nunca mais saiu. Ele fala que ia carregar o mapa.

![WhatsApp Image 2020-11-15 at 10 49 16](https://user-images.githubusercontent.com/74273780/99186613-54d39d00-2730-11eb-8e45-5fae48f9ce39.jpeg)

**Comment by vanerjm** [comment]
Problema de permissão em builds oficiais (release).
